import { useTranslation } from "next-i18next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { GetStaticProps } from "next/types";
import { FC } from "react";
import styles from "../styles/Home.module.css";

export const getStaticProps: GetStaticProps = async ({ locale }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale || "de", ["translation"])),
    },
  };
};

const Home: FC = (props) => {
  console.log(props);
  const router = useRouter();
  const { pathname, asPath, query } = router;
  const onChangeLocale = (nextLocale: string) => {
    router.push({ pathname, query }, asPath, { locale: nextLocale });
  };
  const { t } = useTranslation();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <title>{t("homepage_title", "Ukraine Hilfe Sachsen")}</title>
        <meta name="og:url" content="https://ukraine-hilfe-sachsen.info/" />
        <meta
          name="og:title"
          content={t("homepage_title", "Ukraine Hilfe Sachsen")}
        />
        <meta
          name="og:image"
          content="https://images.unsplash.com/photo-1587027066597-e9b5dea8cbf2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8d3x8fHx8fDE2NDcxMDM2NTk&ixlib=rb-1.2.1&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=640"
        />
      </Head>
      <div className="">
        <h1 className="text-3xl inline-flex md:text-4xl font-extrabold tracking-tight text-gray-900 hover:underline hover:underline-offset-2 hover:cursor-pointer">
          {t("homepage_title", "Ukraine Hilfe Sachsen")}
        </h1>
        <p className="mt-4 text-base text-gray-500">
          {t("homepage_subtitle", "Ich wurde nicht geladen...")}
        </p>
      </div>

      <main className={styles.main}>
        <button onClick={() => onChangeLocale("de")}>DE</button>
        <button onClick={() => onChangeLocale("en")}>EN</button>
        <button onClick={() => onChangeLocale("ru")}>RU</button>
        <button onClick={() => onChangeLocale("uk")}>UK</button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
